# Generated by Django 3.0.7 on 2020-06-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpostapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roastsandboasts',
            old_name='time',
            new_name='createdAt',
        ),
        migrations.AlterField(
            model_name='roastsandboasts',
            name='roastorboast',
            field=models.CharField(choices=[('R', 'Roast'), ('B', 'Boast')], default='R', max_length=1),
        ),
    ]
